package co.com.fcv.training.citas.application;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.sql.Statement;
import java.time.*;
import java.util.*;

@Service
public class AppointmentLifecycleService {
    private static final ZoneId BOGOTA=ZoneId.of("America/Bogota");
    private final JdbcTemplate db;
    public AppointmentLifecycleService(JdbcTemplate db){this.db=db;}

    public List<Map<String,Object>> list(Long user,String status,LocalDate from,LocalDate to){String q=VIEW+" where a.patient_user_id=?";List<Object>p=new ArrayList<>(List.of(user));if(status!=null){q+=" and st.code=?";p.add(status);}if(from!=null){q+=" and a.scheduled_start_at>=?";p.add(from.atStartOfDay());}if(to!=null){q+=" and a.scheduled_start_at<?";p.add(to.plusDays(1).atStartOfDay());}q+=" order by a.scheduled_start_at desc";return views(q,p);}
    public Map<String,Object> detail(Long user,Long id){List<Map<String,Object>>result=listQuery(VIEW+" where a.patient_user_id=? and a.id=?",user,id);if(!result.isEmpty())return result.getFirst();if(count("select count(*) from appointments where id=?",id)>0)throw forbidden("Cita fuera del alcance");throw missing("Cita");}
    @Transactional public void cancel(Long user,Long id,String reason){assertUserAppointment(user,id);Map<String,Object>a=db.queryForMap("select a.scheduled_start_at startAt,s.code status from appointments a join appointment_statuses s on s.id=a.status_id where a.id=? and a.patient_user_id=? for update",id,user);if(!Set.of("APPROVED","REQUESTED").contains(a.get("status"))||!((LocalDateTime)a.get("startAt")).isAfter(LocalDateTime.now(Clock.system(BOGOTA))))throw conflict("La cita no se puede cancelar");String cancellation=reason==null?"Cita cancelada por el usuario":reason;db.update("update rescheduling_requests r join rescheduling_statuses s on s.id=r.status_id set r.status_id=?,r.reason=?,r.decided_by_user_id=?,r.decision_source='USER',r.decided_at=current_timestamp where r.appointment_id=? and s.code='PENDING'",statusIdResched("REJECTED"),cancellation,user,id);db.update("delete rs from rescheduling_slots rs join rescheduling_requests r on r.id=rs.rescheduling_request_id where r.appointment_id=? and r.decided_by_user_id=? and r.decision_source='USER' and r.decided_at is not null",id,user);transition(id,"CANCELLED",user,"USER",reason);db.update("update professional_slots set appointment_id=null where appointment_id=?",id);}
    @Transactional public Map<String,Object> request(Long user,Long id,LocalDate date,LocalTime time){assertUserAppointment(user,id);if(time.getMinute()%30!=0||time.getSecond()!=0||time.getNano()!=0)throw new IllegalArgumentException("La hora debe alinearse a slots de 30 minutos");Map<String,Object>a=db.queryForMap("select a.professional_id professionalId,a.location_id locationId,a.scheduled_start_at startAt,a.scheduled_end_at endAt from appointments a join appointment_statuses s on s.id=a.status_id where a.id=? and a.patient_user_id=? and s.code='APPROVED' for update",id,user);LocalDateTime old=(LocalDateTime)a.get("startAt"),start=LocalDateTime.of(date,time),end=start.plus(Duration.between(old,(LocalDateTime)a.get("endAt")));LocalDateTime now=LocalDateTime.now(Clock.system(BOGOTA));if(!old.isAfter(now)||!start.isAfter(now)||start.equals(old))throw conflict("Cita o nueva franja no válida");if(count("select count(*) from rescheduling_requests r join rescheduling_statuses s on s.id=r.status_id where r.appointment_id=? and s.code='PENDING'",id)>0)throw conflict("Ya existe una solicitud pendiente");List<Long>slots=db.queryForList("select ps.id from professional_slots ps join availability_blocks b on b.id=ps.availability_block_id where b.professional_id=? and b.location_id=? and b.active=true and ps.start_at>=? and ps.end_at<=? and ps.appointment_id is null and not exists(select 1 from rescheduling_slots rs join rescheduling_requests rr on rr.id=rs.rescheduling_request_id join rescheduling_statuses ss on ss.id=rr.status_id where rs.professional_slot_id=ps.id and ss.code='PENDING') order by ps.start_at for update",Long.class,a.get("professionalId"),a.get("locationId"),start,end);int needed=(int)(Duration.between(start,end).toMinutes()/30);if(needed<1||slots.size()!=needed)throw conflict("Nueva franja no disponible");List<LocalDateTime>starts=db.query("select start_at from professional_slots where id in ("+marks(slots.size())+") order by start_at",(r,n)->r.getObject(1,LocalDateTime.class),slots.toArray());for(int i=1;i<starts.size();i++)if(!starts.get(i-1).plusMinutes(30).equals(starts.get(i)))throw conflict("Slots no consecutivos");Long request=insert("insert into rescheduling_requests(appointment_id,status_id,requested_start_at,requested_end_at) values (?,?,?,?)",id,statusIdResched("PENDING"),start,end);try{for(Long slot:slots)db.update("insert into rescheduling_slots(rescheduling_request_id,professional_slot_id) values (?,?)",request,slot);}catch(DuplicateKeyException e){throw conflict("Nueva franja no disponible");}return reschedule(request);}
    public List<Map<String,Object>> pending(Long location,Long professional,Long specialty,LocalDate date){String q="select r.id id,a.id appointmentId,r.requested_start_at startAt,r.requested_end_at endAt,s.code status,r.reason,r.created_at createdAt,r.decided_at decidedAt from rescheduling_requests r join rescheduling_statuses s on s.id=r.status_id join appointments a on a.id=r.appointment_id where s.code='PENDING'";List<Object>p=new ArrayList<>();if(location!=null){q+=" and a.location_id=?";p.add(location);}if(professional!=null){q+=" and a.professional_id=?";p.add(professional);}if(specialty!=null){q+=" and a.specialty_id=?";p.add(specialty);}if(date!=null){q+=" and date(r.requested_start_at)=?";p.add(date);}q+=" order by r.created_at";List<Map<String,Object>>out=new ArrayList<>();for(Map<String,Object>r:db.queryForList(q,p.toArray()))out.add(rescheduleMap(r));return out;}
    @Transactional public Map<String,Object> decide(Long admin,Long id,String decision,String reason){if(!Set.of("APPROVE","REJECT").contains(decision))throw new IllegalArgumentException("Decisión inválida");if("REJECT".equals(decision)&&(reason==null||reason.isBlank()))throw new IllegalArgumentException("Motivo obligatorio");List<Long>appointmentIds=db.query("select appointment_id from rescheduling_requests where id=?",(rs,n)->rs.getLong(1),id);if(appointmentIds.isEmpty())throw missing("Solicitud de reprogramación");Long appointment=appointmentIds.getFirst();Map<String,Object>original=db.queryForMap("select a.id,s.code status from appointments a join appointment_statuses s on s.id=a.status_id where a.id=? for update",appointment);List<Map<String,Object>>pending=db.queryForList("select x.appointment_id appointmentId,x.requested_start_at startAt,x.requested_end_at endAt from rescheduling_requests x join rescheduling_statuses s on s.id=x.status_id where x.id=? and s.code='PENDING' for update",id);if(pending.isEmpty())throw conflict("La solicitud ya fue resuelta");Map<String,Object>r=pending.getFirst();if(!"APPROVED".equals(original.get("status")))throw conflict("La cita ya no está aprobada");if("APPROVE".equals(decision)){db.update("update professional_slots set appointment_id=null where appointment_id=?",appointment);db.update("update professional_slots ps join rescheduling_slots rs on rs.professional_slot_id=ps.id set ps.appointment_id=? where rs.rescheduling_request_id=?",appointment,id);db.update("update appointments set scheduled_start_at=?,scheduled_end_at=? where id=?",r.get("startAt"),r.get("endAt"),appointment);}db.update("update rescheduling_requests set status_id=?,reason=?,decided_by_user_id=?,decision_source='ADMIN',decided_at=current_timestamp where id=?",statusIdResched("APPROVE".equals(decision)?"APPROVED":"REJECTED"),reason,admin,id);db.update("delete from rescheduling_slots where rescheduling_request_id=?",id);return reschedule(id);}
    public List<Map<String,Object>> agenda(Long user,LocalDate from,LocalDate to,Long location){Long professional=db.query("select id from professionals where user_id=? and active=true",(r,n)->r.getLong(1),user).stream().findFirst().orElseThrow(()->missing("Profesional"));String q=VIEW+" where a.professional_id=? and st.code='APPROVED'";List<Object>p=new ArrayList<>(List.of(professional));if(from!=null){q+=" and a.scheduled_start_at>=?";p.add(from.atStartOfDay());}if(to!=null){q+=" and a.scheduled_start_at<?";p.add(to.plusDays(1).atStartOfDay());}if(location!=null){q+=" and a.location_id=?";p.add(location);}q+=" order by a.scheduled_start_at";return views(q,p);}
    @Transactional public void close(Long user,Long id,String status){if(!Set.of("COMPLETED","NO_SHOW").contains(status))throw new IllegalArgumentException("Estado inválido");if(count("select count(*) from appointments where id=?",id)==0)throw missing("Cita");if(count("select count(*) from appointments a join professionals p on p.id=a.professional_id where a.id=? and p.user_id=?",id,user)==0)throw forbidden("Cita fuera del alcance profesional");Map<String,Object>a=db.queryForMap("select a.scheduled_end_at endAt,s.code status from appointments a join professionals p on p.id=a.professional_id join appointment_statuses s on s.id=a.status_id where a.id=? and p.user_id=? for update",id,user);if(!"APPROVED".equals(a.get("status"))||!((LocalDateTime)a.get("endAt")).isBefore(LocalDateTime.now(Clock.system(BOGOTA))))throw conflict("Cita no aplicable");transition(id,status,user,"PROFESSIONAL",null);}
    public List<Map<String,Object>> history(Long actor,Long id,Set<String>roles){String filter="";if(!roles.contains("ADMIN")){List<String>scopes=new ArrayList<>();if(roles.contains("USER"))scopes.add("a.patient_user_id="+actor);if(roles.contains("PROFESSIONAL"))scopes.add("exists(select 1 from professionals p where p.id=a.professional_id and p.user_id="+actor+")");if(scopes.isEmpty())throw forbidden("Rol sin alcance de auditoría");filter=" and ("+String.join(" or ",scopes)+")";}if(count("select count(*) from appointments a where a.id=?"+filter,id)==0){if(count("select count(*) from appointments where id=?",id)==0)throw missing("Cita");throw forbidden("Cita fuera del alcance");}return db.queryForList("select s.code newStatus,h.changed_by_user_id actorId,h.change_source source,h.changed_at timestamp,h.reason from appointment_status_history h join appointment_statuses s on s.id=h.status_id where h.appointment_id=? order by h.changed_at,h.id",id);}

    private static final String VIEW="select a.id,l.id locationId,l.name locationName,p.id professionalId,concat(u.first_name,' ',u.last_name) professionalName,sp.id specialtyId,sp.name specialtyName,a.scheduled_start_at startAt,a.scheduled_end_at endAt,st.code status,a.rejection_reason rejectionReason from appointments a join locations l on l.id=a.location_id join professionals p on p.id=a.professional_id join users u on u.id=p.user_id join specialties sp on sp.id=a.specialty_id join appointment_statuses st on st.id=a.status_id";
    private List<Map<String,Object>>views(String q,List<Object>p){List<Map<String,Object>>out=new ArrayList<>();for(Map<String,Object>r:db.queryForList(q,p.toArray())){Map<String,Object>x=new LinkedHashMap<>();x.put("id",r.get("id"));x.put("location",Map.of("id",r.get("locationId"),"name",r.get("locationName")));x.put("professional",Map.of("id",r.get("professionalId"),"displayName",r.get("professionalName")));x.put("specialty",Map.of("id",r.get("specialtyId"),"name",r.get("specialtyName")));LocalDateTime s=(LocalDateTime)r.get("startAt"),e=(LocalDateTime)r.get("endAt");x.put("date",s.toLocalDate());x.put("startTime",s.toLocalTime());x.put("endTime",e.toLocalTime());x.put("durationMinutes",Duration.between(s,e).toMinutes());x.put("status",r.get("status"));if(r.get("rejectionReason")!=null)x.put("rejectionReason",r.get("rejectionReason"));out.add(x);}return out;}
    private List<Map<String,Object>>listQuery(String q,Object...p){return views(q,Arrays.asList(p));}
    private Map<String,Object>reschedule(Long id){return rescheduleMap(db.queryForMap("select r.id id,r.appointment_id appointmentId,r.requested_start_at startAt,r.requested_end_at endAt,s.code status,r.reason,r.created_at createdAt,r.decided_at decidedAt from rescheduling_requests r join rescheduling_statuses s on s.id=r.status_id where r.id=?",id));}
    private Map<String,Object>rescheduleMap(Map<String,Object>r){LocalDateTime start=(LocalDateTime)r.get("startAt"),end=(LocalDateTime)r.get("endAt");Map<String,Object>m=new LinkedHashMap<>();m.put("id",r.get("id"));m.put("appointmentId",r.get("appointmentId"));m.put("requestedDate",start.toLocalDate());m.put("requestedStartTime",start.toLocalTime());m.put("requestedEndTime",end.toLocalTime());m.put("status",r.get("status"));if(r.get("reason")!=null)m.put("reason",r.get("reason"));m.put("createdAt",r.get("createdAt"));if(r.get("decidedAt")!=null)m.put("decidedAt",r.get("decidedAt"));return m;}
    private void transition(Long appointment,String status,Long actor,String source,String reason){Long sid=statusId(status);db.update("update appointments set status_id=? where id=?",sid,appointment);history(appointment,sid,actor,source,reason);}
    private void history(Long a,Long s,Long actor,String source,String reason){db.update("insert into appointment_status_history(appointment_id,status_id,changed_by_user_id,change_source,reason) values (?,?,?,?,?)",a,s,actor,source,reason);}
    private Long statusId(String code){return db.queryForObject("select id from appointment_statuses where code=?",Long.class,code);}private Long statusIdResched(String code){return db.queryForObject("select id from rescheduling_statuses where code=?",Long.class,code);}
    private void assertUserAppointment(Long user,Long id){if(count("select count(*) from appointments where id=?",id)==0)throw missing("Cita");if(count("select count(*) from appointments where id=? and patient_user_id=?",id,user)==0)throw forbidden("Cita fuera del alcance del usuario");}
    private Long insert(String sql,Object...args){KeyHolder k=new GeneratedKeyHolder();db.update(c->{var s=c.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS);for(int i=0;i<args.length;i++)s.setObject(i+1,args[i]);return s;},k);return Objects.requireNonNull(k.getKey()).longValue();}
    private int count(String q,Object...p){Integer n=db.queryForObject(q,Integer.class,p);return n==null?0:n;}private String marks(int n){return String.join(",",Collections.nCopies(n,"?"));}
    private SchedulingFailure missing(String s){return new SchedulingFailure(SchedulingFailure.Kind.NOT_FOUND,s+" no encontrado");}private SchedulingFailure forbidden(String s){return new SchedulingFailure(SchedulingFailure.Kind.FORBIDDEN,s);}private SchedulingFailure conflict(String s){return new SchedulingFailure(SchedulingFailure.Kind.CONFLICT,s);}
}
